# Use the file format compatible with Docker Compose 3.8
version: "3.8"

services:

  database:
    image: postgres:11.5

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
        - "5432:5432"   

  web:
    build: .

    volumes:
      - .:/code:cached

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    ports:
      - "3000:3000"

    depends_on:
      - database

    environment:
      RAILS_ENV: development
      DATABASE_NAME: kr_db
      DATABASE_USER: kr_db
      DATABASE_PASSWORD: 
      DATABASE_HOST: database

volumes:
  db_data: